version: '3.9'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.dockerfile
#    image: jenkins/jenkins:latest
    ports:
      - "8081:8080"
      - "50000:50000"
    container_name: jenkins_c
    volumes:
      - jenk_vol2:/var/jenkins_home

volumes:
  jenk_vol2:
